version: 2

jobs:
  build:
    docker:
      - image: tatsy/ubuntu-cxx 
    steps:
      - checkout
      - run:
          name: build
          command: cmake .; make
      - test
test:
  override:
    - ./build/tp 
