version: 2

jobs:
  build:
    docker:
      - image: gcc:latest 
    steps:
      - checkout
      - run:
          name: cmake
          command: cmake .
      - run:
          name: make
          command: make
