version: 2

jobs:
  dependencies:
    pre:
      - sudo apt-get install cmake make
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: cmake
          command: cmake .
      - run:
          name: make
          command: make
