version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
      - dependencies:
          pre:
              - sudo apt-get update; sudo apt-get install cmake make
          name: cmake
          command: cmake .
      - run:
          name: make
          command: make
