version: 2

dependencies:
    override:
        - sudo apt-get update 
        - sudo apt-get install cmake make
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: cmake
          command: cmake .
      - run:
          name: make
          command: make
