version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - compile:
          override: cmake . & make
      - run:
	  name: run
          command: ./build/tp

