version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: cmake
          command: cmake .
      - run:
          name: make
          command: make
